source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

project 'FA_TokenInputView'

target 'FA_TokenInputView_Example' do
  pod "FA_TokenInputView", :path => "../"
end

target 'FA_TokenInputView_Tests' do
  pod "FA_TokenInputView", :path => "../"
end
