source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'FA_TokenInputView_Example', :exclusive => true do
  pod "FA_TokenInputView", :path => "../"
end

target 'FA_TokenInputView_Tests', :exclusive => true do
  pod "FA_TokenInputView", :path => "../"

  
end
